### ISSUE TITLE
Countries without mobile-begin-with values may fail to validate

### ISSUE THREAD

**Issue by allendav** [AfterShip/node-phone#26]
If you call the module with a phone number but not a country, and the phone number includes a country code (e.g. +54 for Argentina) and the country doesn't have any `mobile_begin_with` values, then the internal function `get_iso3166_by_phone` will fail to return an iso3166 entry and valid phone numbers for that country will fail to validate.

**Comment by teddychan** [comment]
We have reason to do that.

Since this module is to verify mobile phone number.

If a country code is given, and without mobile_begin_with.
There is chance that the phone number actually is a land line number.

Since we use this module to send out SMS, some sms provider charge no matter what phone number you sent.

make sense?

**Comment by allendav** [comment]
That's a good point.  I'll see if we can use the phone number + country interface instead for what we're trying to accomplish.

**Comment by teddychan** [comment]
we are working on the 2.0 version, which can give more info (if it is mobile or land)
as well as format the phone number into `country_code`, `area_code`

feel free to give feedback https://github.com/AfterShip/node-phone/tree/2.x#usage-2x-branch

I will close this issue first
